import { ReactNode } from 'react';
import type { NextComponentType } from 'next';

import Head from 'next/head';

type Props = {
  title?: string
  children?: ReactNode
};

const defaultProps = {
  title: 'Weather',
  children: null,
};

const HtmlHead: NextComponentType<Props> = ({ title, children }) => (
  <Head>
    <title>{title}</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
    {children}
  </Head>
);

HtmlHead.defaultProps = defaultProps;

export default HtmlHead;
